### PR TITLE
Update CSS and content

### PR DESCRIPTION
**Pull request by f3rn0s**
Current state of the CSS re-do, lots of placeholders (i.e. backgrounds). It also has some other stuff that should've been it's own branch (whoops) but is good to do (i.e. clean up blog post's headings so they actually render).

### CODE REVIEW

**Comment by pi3ch** [comment]
@f3rn0s would you mind look into these merge conflicts?

**Comment by f3rn0s** [comment]
@pi3ch I've fixed up the merge conflicts, but we should probably sit down and iron out the background colors before we merge this in :).

**Comment by pi3ch** [comment]
@f3rn0s I suggest we keep the background white for now (the most inclusive color) so we get your changes in.

**Comment by f3rn0s** [comment]
Apologies for the delay on this, I've replaced the backgrounds with a subtle off-white gradient:

image

**Pull request merged**
